#!/bin/bash

#graphsize=(10 50 100 500 1000 2000)
#threads_num=(0 1 2 4 8 16 32 64 128)
graphsize=(2000)
threads_num=(128)
max_gap=5
program="../code/apps/outdir/app-cli-release"
output_file="results.csv"
itercount=10

echo -n "graphsize" > $output_file
for p in "${threads_num[@]}"; do
    echo -n ";par$p" >> $output_file
done
echo "" >> $output_file

for size in "${graphsize[@]}"; do
    echo -n "$size" >> $output_file
    for thread in "${threads_num[@]}"; do
        result=$($program "$size.gv" "$max_gap" "$thread" "$itercount")
        echo -n ";$result" >> $output_file
    done
    echo "" >> $output_file
done
