#!/bin/bash

graphsize=(100)
threads_num=(0 1 2 4 8 16 32 64 128)
input_string="example"
max_gap=5
program="../code/apps/outdir/app-cli-release"
output_file="results.csv"

echo -n "graphsize" > $output_file
for p in "${threads_num[@]}"; do
    echo -n ";par$p" >> $output_file
done
echo "" >> $output_file

for size in "${graphsize[@]}"; do
    python3 gen.py "$size" > tmp.gv
    echo -n "$size" >> $output_file
    for thread in "${threads_num[@]}"; do
        result=$($program "tmp.gv" "$max_gap" "$size" "$thread" "--measure")
        echo -n ";$result" >> $output_file
    done
    echo "" >> $output_file
done
